### PR TITLE
Fix Windows CI

### PR DESCRIPTION
**Pull request by ptoffy**
Add a platform check to `scrypt` which replaces `sysconf` with its Windows counterpart to make Windows CI pass

### CODE REVIEW

**Review by Lukasa — APPROVED** [review]
Thanks @ptoffy!

**Comment by Lukasa** [comment]
And great timing, @FranzBusch just added the windows CI pipeline. Let's see what this looks like.

**Comment by FranzBusch** [comment]
The tests build and run now but we have numerous failures.

**Comment by Lukasa** [comment]
Yeah, we knew that we had CI failures. Paul was only trying to get the build to pass, so we can merge this as-is. WE'll need to fix the Windows CI failures, of course, but at least we now have a CI system that is capable of locking in the win.

**Pull request merged**
