### PR TITLE
build: repair the CMake build

### PR DESCRIPTION
**Pull request by compnerd**
The update to BoringSSL removed the modulemap which is required for the
CMake build.

_[One line description of your change]_

### Checklist
- [ ] I've run tests to see all new and existing tests pass
- [ ] I've followed the code style of the rest of the project
- [ ] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary

#### If you've made changes to `gyb` files
- [ ] I've run `.script/generate_boilerplate_files_with_gyb` and included updated generated files in a commit of this pull request

### Motivation:

_[Explain here the context, and why you're making that change. What is the problem you're trying to solve.]_

### Modifications:

_[Describe the modifications you've done.]_

### Result:

_[After your change, what will change.]_

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @Lukasa @yim-lee @tomerd

**Review by Lukasa — CHANGES_REQUESTED** [review]
This requires an adjustment to the `scripts/vendor_boringssl.sh` script to place this file back at the root, or otherwise arrange for it to be persisted. Otherwise this will continue to be deleted.

**Comment by Lukasa** [comment]
Also, while we're here: "required for the cmake build"? Why didn't CI fail?

**Comment by yim-lee** [comment]
> Why didn't CI fail?

We don't have a CI job that run the cmake build actually. Let me look into setting it up.

**Comment by yim-lee** [comment]
@Lukasa Would this do? https://github.com/apple/swift-crypto/pull/69

I will look into setting up CI next, but can we merge this PR merge first to fix things?

**Comment by yim-lee** [comment]
CI setup: https://github.com/apple/swift-crypto/pull/70

**Comment by yim-lee** [comment]
CI probably confused and linked 5.3-prb to the new cmake-prb, which is expected to fail for this PR since it doesn't contain the new docker-compose file.

@swift-server-bot test this please

**Comment by yim-lee** [comment]
Thanks @compnerd for catching this. https://github.com/apple/swift-crypto/pull/70 includes the modulemap as well.

**Comment by Lukasa** [comment]
Closing in favour of #70.

**Pull request closed without merging**
