### PR TITLE
fix a typo in documentation

### PR DESCRIPTION
**Pull request by tremblay**
Fixes a typo in the documentation, where `SymmetricKeySize.bits192` is incorrectly described as having 128 bits

### Checklist
- [N/A] I've run tests to see all new and existing tests pass
- [N/A] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [x] I've updated the documentation if necessary

#### If you've made changes to `gyb` files
- [N/A] I've run `.script/generate_boilerplate_files_with_gyb` and included updated generated files in a commit of this pull request

### Motivation:

Enhances clarity in the `SymmetricKeySize` enum

### Modifications:

Just changed 2 characters in the documentation to accurately reflect the key size

### Result:

Correct key size in the documentation

### CODE REVIEW

**Review by Lukasa — APPROVED** [review]
Yup, sure looks wrong to me. Thanks!

**Comment by Lukasa** [comment]
@swift-server-bot test this please

**Comment by Lukasa** [comment]
@swift-server-bot test this please

**Comment by Lukasa** [comment]
Hmm, 5.3 broken because of Jenkins. Let me try once more.

**Comment by Lukasa** [comment]
@swift-server-bot test this please

**Comment by Lukasa** [comment]
@tomerd Any idea what's up with the 5.3 executor here?

**Review by FredericJacobs — APPROVED** [review]
Good catch!

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
> @tomerd Any idea what's up with the 5.3 executor here?

@Lukasa offloaded it, lmk if you see it again

**Comment by Lukasa** [comment]
Thanks @tomerd!

**Pull request merged**
