### PR TITLE
build: add amd64 and aarch64 assembly files to CMake build for Android

### PR DESCRIPTION
**Pull request by buttaface**
### Checklist
- [x] I've run tests to see all new and existing tests pass
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary

### Motivation:

Get all needed functions built for Android.

### Modifications:

Two small CMake additions

### Result:

The CMake build of the May 3rd trunk snapshot of SPM on Android AArch64 works again.

The amd64 change has not been tested, but will likely be needed too.

### CODE REVIEW

**Comment by Lukasa** [comment]
Thanks for this patch! This CMakeLists.txt file is auto-generated from https://github.com/apple/swift-crypto/blob/main/scripts/update_cmakelists.sh: can you update the script and re-run it to validate that it produces the result we want?

**Comment by buttaface** [comment]
All that script does is update the list of BoringSSL files in the existing CMake config: I ran it on this patched version and it gave the same CMake config.

**Comment by Lukasa** [comment]
@swift-server-bot test this please

**Review by Lukasa — COMMENTED** [review]
@buttaface Thanks for validating that!

**Review by yim-lee — APPROVED** [review]

**Comment by yim-lee** [comment]
https://ci.swiftserver.group/job/swift-crypto-cmake-prb/25/console

```
<unknown>:0: error: module file '/tmp/org.llvm.clang.0/ModuleCache/QWQG002B74NX/SwiftShims-1KFO504FT44T.pcm' is out of date and needs to be rebuilt: signature mismatch
<unknown>:0: note: imported by module 'SwiftOverlayShims' in '/tmp/org.llvm.clang.0/ModuleCache/QWQG002B74NX/SwiftOverlayShims-1KFO504FT44T.pcm'
<unknown>:0: error: missing required module 'SwiftOverlayShims'
```

@swift-server-bot test this please

**Comment by buttaface** [comment]
Ping, anything holding this back?

**Comment by Lukasa** [comment]
Nope! ❇️

**Pull request merged**
