### PR TITLE
build: add `ARM64` spelling for Windows

### PR DESCRIPTION
**Pull request by compnerd**
Windows uses `ARM64` for the `CMAKE_SYSTEM_PROCESSOR` which does not match the existing spellings.  Add the special case for Darwin while in the area.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-server-bot please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by Lukasa** [comment]
Tagging @yim-lee for review.

**Review by yim-lee — APPROVED** [review]

**Comment by yim-lee** [comment]
@Lukasa Can we cut a release for this patch and https://github.com/apple/swift-crypto/pull/144 please? Thanks in advance.

**Comment by Lukasa** [comment]
Shipped as 2.3.0.

**Pull request merged**
