### PR TITLE
Updating file headers

### PR DESCRIPTION
**Pull request by Sajjon**
Updating headers of all files

### Motivation:

The file is not named  `CONTRIBUTORS.txt` anymore.

### Modifications:

1. Search replace "CONTRIBUTORS.txt" -> "CONTRIBUTORS.md"

### Result:

Correct reference.

### CODE REVIEW

**Comment by Sajjon** [comment]
Additional cleanup of headers:
1. As per https://github.com/apple/swift-crypto/pull/12/files, we might also wanna replace _"SwiftCrypto"_ with _"Swift Crypto"_ (in headers,)
2. Should we maybe give proper markdown rendering to the license file as well? I.e. renaming `LICENSE.txt` -> `LICENSE.md` so Xcode renders it nicely. If so we ought to update this in the headers as well.

**Comment by Lukasa** [comment]
For now let's leave the project name as `SwiftCrypto` in the license files. It's inconsistent with our public styling but not in a way that affects anything. I'd also like to leave the license file as a .txt, as it's not really markdown and we don't need the fancy rendering. So I think this patch is G2G.

**Comment by Sajjon** [comment]
Agreed!

**Comment by Lukasa** [comment]
Cool, this should be adopted on top of master.

**Comment by Sajjon** [comment]
Rebasing now

**Comment by Sajjon** [comment]
Good to go 🕺

**Comment by Lukasa** [comment]
@swift-server-bot test this please

**Comment by Sajjon** [comment]
@Lukasa haha I forgot changing back to `.md` in `environment.sh` script after rebasing of course 😄 , fixed now.

**Comment by Lukasa** [comment]
@swift-server-bot test this please

**Pull request merged**
