### PR TITLE
Update wycheproof testvectors to v1

### PR DESCRIPTION
**Pull request by Sajjon**
Update some Wycheproof [testvectors (v0)](https://github.com/google/wycheproof/tree/master/testvectors) to new [testvectors_v1](https://github.com/google/wycheproof/tree/master/testvectors_v1), which in general include more tests per file.

### Checklist
- [x] I've run tests to see all new and existing tests pass
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [x] I've updated the documentation if necessary

#### If you've made changes to `gyb` files
- [ ] I've run `.script/generate_boilerplate_files_with_gyb` and included updated generated files in a commit of this pull request

### Motivation:

We ought to use as many and as up to date test vectors as possible. Wycheproofs v0 were created 4 years ago and were due some upgrade.

### Modification & Result
(I took the liberty to merge these to sections together)

More tests are now run 🎉 below is a table over all changes and result.

| Testvector  | Previous name | V0 number of tests | V1 number of tests | Source code unchanged? | Test code unchanged? | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| `x25519_test`  | unchanged | 87  | 518 | ✅ | ✅ | 
| `ed25519_test` | `eddsa_test`  | 111 |  150 |  ✅ | JSON: changed single key |
| `aes_gcm_test ` | unchanged  | 217 |  313 | ✅ | ✅ | 
| `chacha20_poly1305_test` | unchanged  | 151 |  325 | ✅ | ✅ | 
| `ecdh_secp256r1_ecpoint_test`  | unchanged | 99 |  355 | ✅ | ✅ | 
| `ecdh_secp256r1_test`  | unchanged | 340 |  612 | ✅ | Logic: `fatalError` -> failable init | 

# I can upgrade all...
... but I wanted to hear first that you think it a good idea... 

If so, should I do it in a single PR? I.e. add more commits to this PR?

### CODE REVIEW

**Comment by Sajjon** [comment]
@swift-server-bot test this please

**Comment by Sajjon** [comment]
Ah maybe I lack access to trigger swift-server-bot to run tests... one can always try 😅

**Comment by Sajjon** [comment]
@Lukasa would you be interested in me continuing with the rest of the vectors? I mean to say, if you don't think it a good idea, best I don't waste the time 😅.

If you think it it a good idea, do you prefer all upgraded in the same PR? Or split across many?

Let me know :)

**Comment by Sajjon** [comment]
@Lukasa I've split this PR into six new ones, I will continue with the rest later next week. Should we have an umbrella issue for all PRs? Since they are strongly related. I can create that, and then we can close this PR.

Let me know how you wanna proceed! :)

**Comment by Lukasa** [comment]
The first 6 are merged, thanks!

**Pull request closed without merging**
